version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - local-mongo:/data/db

  # Redis service
  redis:
    image: "redis:latest"
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    depends_on:
      - mongodb
      - redis
    container_name: "backend"
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "2999:2999"
      - "3000:3000"
      - "3001:3001"
      - "3010:3010"
      - "3011:3011"
      - "3012:3012"
    environment:
      - "NODE_ENV=development"

  frontend:
    depends_on: 
      - mongodb
      - redis
    container_name: "frontend"
    restart: unless-stopped
    build:
      context: ./react_main
      dockerfile: dockerfile
    ports:
      - "80:80"
    environment:
      - "NODE_ENV=development"
volumes:
  local-mongo: