version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - local-mongo:/data/db

  # Redis service
  redis:
    image: "redis:latest"
    restart: unless-stopped
    ports:
      - "6379:6379"
  app:
    depends_on:
      - mongodb
      - redis
    image: keymetrics/pm2:14-slim
    environment:
      - NODE_ENV=development
    working_dir: /home/um
    command:
      - /bin/sh
      - -cx
      - |
        cd /home/um && npm install
        cd /home/um/react_main && npm install
        cd /home/um/react_main && npm run build && rm -rf /home/um/react_main/build_public && mv /home/um/react_main/build /home/um/react_main/build_public
        cd /home/um/react_main && npm start
    restart: unless-stopped
    ports:
      - 2999
      - 3000
      - 3010
      - 3001
    volumes:
      - ./:/home/um
    networks:
      - default
volumes:
  local-mongo:
